[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Implementation of a DKG"
documentation = ""
edition = "2018"
exclude = [""]
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "bls_dkg"
readme = "README.md"
repository = "https://github.com/maidsafe/BLS-DKG"
version = "0.1.0"

[dependencies]
aes = "^0.3.2"
bincode = "^1.1.4"
block-modes = "^0.3.3"
err-derive = "^0.2.4"
itertools = "0.9.0"
rand = "^0.7.3"
rand_core = "^0.2.1"
serde = "^1.0.106"
serde_derive = "^1.0.106"
threshold_crypto = "^0.3.2"
